//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 MyRemoteTool-ui.rc 使用
//
#define IDD_DIALOG_PSWDINPUT            102
#define IDC_EDIT_PSWDDLG_PASSWORD       1001
#define IDR_MENU_CLTMAIN                2301
#define ID_CLTMAIN_FILE_NEWSESSION      40018
#define ID_CLTMAIN_FILE_OPENSESSION     40019
#define ID_CLTMAIN_RECENTSESSIONS_CLEAR 40020
#define ID_CLTMAIN_FILE_SAVESESSION     40021
#define ID_CLTMAIN_FILE_SAVESESSIONAS   40022
#define ID_CLTMAIN_FILE_CLOSE           40023
#define ID_CLTMAIN_FILE_EXIT            40024
#define ID_CLTMAIN_WINDOW_CLOSE         40026
#define ID_CLTMAIN_HELP_GETHELP         40028
#define ID_CLTMAIN_HELP_DOC             40029
#define ID_CLTMAIN_HELP_ABOUT           40030
#define ID_CLTMAIN_LICENSE_LICENSE      40032
#define ID_CLTMAIN_PROJECTLOCATION      40033
#define ID_CLTMAIN_SHELLABOUT           40034
#define ID_CLTMAIN_HELP_ENABLEDEBUG     40037
#define ID_CLTMAIN_FORCESETBCONLIVE_F   40045
#define ID_CLTMAIN_FORCESETBCONLIVE_T   40046
#define ID_CLTMAIN_HELP_INSPECTSCITER   40052
#define ID_CLTMAIN_FOCUSINBROWSER       40054
#define ID_CLTMAIN_VIEW_FULLSCREEN      40062
#define ID_CLTMAIN_SETTINGS             40070
#define ID_CLTMAIN_EDIT                 40071
#define ID_CLTMAIN_COPY                 40072
#define ID_CLTMAIN_PASTE                40073
#define ID_CLTMAIN_FIND                 40074
#define ID_CLTMAIN_REPLACE              40075
#define ID_CLTMAIN_DISCONNECT           40078
#define ID_CLTMAIN_WINDOW_RELOAD        40080
#define ID_RECENTSESSIONS_RECENTSESSIONS 40081

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40082
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
