//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 str_table.rc 使用
//
#define IDS_STRING_APP_UUID             1301
#define IDS_STRING_APP_GUID             1302
#define IDS_STRING_SVC_DEFAULT_NAME     1321
#define IDS_STRING_SVC_DEFAULT_DISPLAY_NAME 1322
#define IDS_STRING_SVC_DEFAULT_DESCRIPTION 1323
#define IDS_STRING_SVC_DEPENDENCIES     1324
#define IDS_STRING_NETWORK_DEFAULTPORT  1341
#define IDS_STRING_UI_SETUPWINDOW_CLASS 1361
#define IDS_STRING_UI_SETUPWINDOW_TITLE 1362
#define IDS_STRING_SRV_USERFILE_LOCATION 1401
#define IDS_STRING_SRV_CONFIG_MEMMAP_NAME 1402
#define IDS_STRING_SRV_AUTHSRV_NAME     1403

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
